Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -23,7 +23,7 @@ jobs:
 
     - name: Build and tag Docker image
       run: |
-        docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/chic_25_jamovi_be:latest .
+        docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/chic_25_jamovi_be:latest --build-arg ENV_FILE=.env .
         docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/chic_25_jamovi_be:latest ${{ secrets.DOCKER_HUB_USERNAME }}/chic_25_jamovi_be:latest
 
     - name: Push Docker image to Docker Hub
@@ -57,13 +57,16 @@ jobs:
         echo "SSH command: ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST"
         echo "!!"
     
+        # Create .env file on the server
+        sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo '${{ secrets.ENV }}' > .env"
+        
         sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
         echo "succeed ssh login"
           IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/chic_25_jamovi_be:latest"
           sudo docker pull $IMAGE
           sudo docker stop chic_25_jamovi_be || true
           sudo docker rm chic_25_jamovi_be || true
-          sudo docker run -d --name chic_25_jamovi_be -p 8000:8000 --env-file .env $IMAGE || echo "Failed to start container"
+          sudo docker run -d --name chic_25_jamovi_be -p 8000:8000 -v $(pwd)/.env:/app/.env $IMAGE || echo "Failed to start container"
           sudo docker logs chic_25_jamovi_be
           sudo docker system prune -af
         EOF
